name: scrape

on:
  schedule:
    - cron: '0 5,17 * * *'

jobs:
  home:
    runs-on: ubuntu-latest
    steps:
      - name: Scrape Enbridge Gas
        env:
          DRAKMA_URL: ${{ secrets.DRAKMA_URL }}
          DRAKMA_TOKEN: ${{ secrets.DRAKMA_TOKEN }}
          HOME_DRAKMA_ACCOUNT: ${{ secrets.HOME_DRAKMA_ACCOUNT }}
          HOME_ENBRIDGE_GAS_USERNAME: ${{ secrets.HOME_ENBRIDGE_GAS_USERNAME }}
          HOME_ENBRIDGE_GAS_PASSWORD: ${{ secrets.HOME_ENBRIDGE_GAS_PASSWORD }}
        run: |
          docker run --rm zylphrex/drakma-cli:latest drakma-cli enbridge --headless=1 --url="${DRAKMA_URL}" --token="${DRAKMA_TOKEN}" --account="${HOME_DRAKMA_ACCOUNT}" --username="${HOME_ENBRIDGE_GAS_USERNAME}" --password="${HOME_ENBRIDGE_GAS_PASSWORD}"
